# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gateway.apigee_grpc._proto import external_callout_pb2 as gateway_dot_apigee__grpc_dot___proto_dot_external__callout__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway/apigee_grpc/_proto/external_callout_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExternalCalloutServiceStub:
    """The ExternalCalloutService can be used to build gRPC-based Apigee Edge
    policies.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessMessage = channel.unary_unary(
                '/apigee.ExternalCalloutService/ProcessMessage',
                request_serializer=gateway_dot_apigee__grpc_dot___proto_dot_external__callout__pb2.MessageContext.SerializeToString,
                response_deserializer=gateway_dot_apigee__grpc_dot___proto_dot_external__callout__pb2.MessageContext.FromString,
                _registered_method=True)


class ExternalCalloutServiceServicer:
    """The ExternalCalloutService can be used to build gRPC-based Apigee Edge
    policies.
    """

    def ProcessMessage(self, request, context):
        """This method takes a MessageContext and returns a modified MessageContext.
        See the commentary on MessageContext for how to use it.

        The exceptions thrown by the implementation of the gRPC service will be
        translated into faults by the message processor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalCalloutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessMessage,
                    request_deserializer=gateway_dot_apigee__grpc_dot___proto_dot_external__callout__pb2.MessageContext.FromString,
                    response_serializer=gateway_dot_apigee__grpc_dot___proto_dot_external__callout__pb2.MessageContext.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apigee.ExternalCalloutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('apigee.ExternalCalloutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExternalCalloutService:
    """The ExternalCalloutService can be used to build gRPC-based Apigee Edge
    policies.
    """

    @staticmethod
    def ProcessMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apigee.ExternalCalloutService/ProcessMessage',
            gateway_dot_apigee__grpc_dot___proto_dot_external__callout__pb2.MessageContext.SerializeToString,
            gateway_dot_apigee__grpc_dot___proto_dot_external__callout__pb2.MessageContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
